export type TabletProduct = {
  code: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  highlights: string[];
  galleryCount: number;
  detailCount: number;
  specs: [string, string][];
  faqs: [string, string][];
  kids?: boolean;
};

export const tabletProducts: Record<string, TabletProduct> = {
  "wb-tb-01": {
    code: "GT35", title: "10.95\" Android Tablet OEM | Android 14, 4GB/128GB | Weiboer", h1: "10.95-inch Android Learning Tablet — OEM / ODM Ready", eyebrow: "ANDROID 14 · 10.95-INCH LEARNING TABLET", description: "A practical Android learning tablet for training rooms, business deployment and education programs. Configure storage, camera, logo and packaging for your market.", highlights: ["Android 14", "10.95-inch display", "4GB RAM + 128GB storage", "WiFi + Bluetooth"], galleryCount: 6, detailCount: 10,
    specs: [["Display", "10.95-inch display, 1280 × 800 listed resolution"], ["Operating System", "Android 14"], ["CPU", "Spreadtrum T606, 1.6GHz"], ["Graphics", "Dual A75 1.6GHz + six A55 1.6GHz cores listed"], ["Memory", "4GB RAM"], ["Storage", "128GB"], ["Wireless", "WiFi + Bluetooth"], ["Battery", "3.8V / 6000mAh, 4-5 hours listed"], ["Use Case", "Business, training and education"], ["Condition", "New"], ["Customization", "Private mold, logo and packaging options"], ["MOQ", "1 pc for sample · bulk pricing available"]],
    faqs: [["Which Android version does it use?", "WB-TB-01 is listed with Android 14 and a Spreadtrum T606 platform."], ["Can the storage be customized?", "The listing specifies 128GB storage. Confirm storage and camera variants with our team before production."], ["Can I add my own logo?", "Yes. Weiboer supports logo, boot logo, packaging and language customization for OEM programs."], ["What is the MOQ?", "The listing supports sample orders from 1 unit. Contact us for bulk pricing."], ["Is it suitable for education projects?", "Yes. Its Android learning platform and low-MOQ supply make it suitable for training and education programs."]]
  },
  "wb-tb-02": {
    code: "GT70", title: "11.97\" 4G Android Tablet OEM | 6GB/256GB, 13MP Camera | Weiboer", h1: "11.97-inch 4G Camera Tablet — OEM / ODM Ready", eyebrow: "ANDROID 13 · 4G CAMERA TABLET", description: "A large-screen 4G Android tablet for field reporting, business communication and daily professional use. Up to 6GB RAM, 256GB storage and a 13MP rear camera.", highlights: ["Android 13", "4G + WiFi", "6GB RAM + 128/256GB", "13MP rear camera"], galleryCount: 6, detailCount: 12,
    specs: [["Display", "11.97-inch, 1200 × 2000"], ["Operating System", "Android 13"], ["CPU", "Spreadtrum T616, 2.0GHz"], ["Graphics", "Mali-G57-3EE listed"], ["Memory", "6GB RAM"], ["Storage", "128GB / 256GB"], ["Wireless", "WiFi + 4G, Bluetooth"], ["Camera", "13MP rear camera listed"], ["Battery", "8000mAh / 3.8V, 6-10 hours listed"], ["Dimensions", "278.5 × 174 × 7.5mm"], ["Features", "Dustproof, drop-resistant shell, NFC listed"], ["MOQ", "1 pc for sample · bulk pricing available"]],
    faqs: [["Does it support 4G?", "Yes. The listing supports WiFi and 4G connectivity for mobile professional use."], ["Which storage options are available?", "128GB and 256GB storage variants are listed, with 6GB RAM."], ["Is the rear camera 13MP?", "The product title and specification table list a 13MP rear camera."], ["Can it be branded?", "Yes. Logo, packaging, language and selected hardware configurations can be discussed for OEM programs."], ["What is the MOQ?", "Sample orders start at 1 unit; contact us for bulk pricing."]]
  },
  "wb-tb-03": {
    code: "IP17", title: "10.1\" 4G Android Tablet OEM | 4GB RAM, 128GB | Weiboer", h1: "10.1-inch 4G Android Tablet — OEM / ODM Ready", eyebrow: "ANDROID 12 · 10.1-INCH 4G TABLET", description: "A brand-new 10.1-inch IPS Android tablet for business and mobile deployment. The platform supports 4G, expandable storage and multiple memory configurations.", highlights: ["Android 12", "10.1-inch IPS", "4GB + 32/64/128GB", "4G + expandable storage"], galleryCount: 6, detailCount: 11,
    specs: [["Display", "10.1-inch IPS, 1280 × 800"], ["Operating System", "Android 12 listed in primary product data"], ["CPU", "MTK6762 octa-core"], ["Network", "2G / 3G / 4G listed"], ["Memory", "4GB RAM"], ["Storage", "32GB / 64GB / 128GB, TF expansion up to 128GB"], ["Camera", "5MP front + 13MP rear listed in primary data; confirm final module"], ["Touch", "Capacitive touchscreen"], ["Battery", "6000mAh listed in primary data; confirm final battery"], ["Interface", "USB Type-C"], ["Weight", "1.2kg net listed"], ["MOQ", "1 pc for sample · bulk pricing available"]],
    faqs: [["Which Android version is final?", "The primary product data lists Android 12; one embedded description table shows Android 11, so confirm the final OS image before production."], ["What camera options are available?", "The primary data lists 5MP front and 13MP rear; confirm the final camera module for your order."], ["Does it support 4G?", "Yes. The listing supports 2G/3G/4G network configurations."], ["Can storage be expanded?", "The listing supports TF card expansion up to 128GB."], ["Can I request OEM branding?", "Yes. Logo, packaging and language customization can be discussed."]]
  },
  "wb-tb-04": {
    code: "R17", title: "10.1\" Android Tablet OEM | 3GB/32GB, 4G Calling | Weiboer", h1: "10.1-inch Android Business Tablet — OEM / ODM Ready", eyebrow: "ANDROID 10 · BUSINESS TABLET", description: "An entry-level 10.1-inch Android tablet for everyday business, calling and mobile deployment. Supports 4G, WiFi, Bluetooth and custom private-label programs.", highlights: ["Android 10", "10.1-inch display", "3GB RAM + 32GB", "4G calling + WiFi"], galleryCount: 6, detailCount: 14,
    specs: [["Display", "10.1-inch listed; resolution shown as 1280 × 1080 in seller data, confirm final panel"], ["Operating System", "Android 10"], ["CPU", "MediaTek MTK6750 octa-core, 1.2GHz"], ["Network", "WiFi + 4G calling"], ["Memory", "3GB RAM"], ["Storage", "32GB"], ["Wireless", "WiFi + Bluetooth 5.0 listed"], ["Features", "Dustproof, drop-resistant shell, NFC listed"], ["Battery", "5000mAh"], ["Use Case", "Business and everyday mobile use"], ["Condition", "New"], ["MOQ", "1 pc for sample · bulk pricing available"]],
    faqs: [["Does it support 4G calling?", "Yes. The listing specifies WiFi, 4G calling and Bluetooth connectivity."], ["What are the memory options?", "The listed configuration is 3GB RAM with 32GB storage."], ["Is the display resolution confirmed?", "The listing displays 1280 × 1080, which is unusual for this size. Confirm the final panel resolution before production."], ["Can the enclosure be branded?", "Yes. Weiboer supports logo, packaging and language customization."], ["What is the MOQ?", "Sample orders start from 1 unit."]]
  },
  "wb-tb-05": {
    code: "KM03", title: "7\" Kids Android Tablet OEM | WiFi, 1GB/16GB Learning Pad | Weiboer", h1: "7-inch Kids Educational Tablet — OEM / ODM Ready", eyebrow: "KIDS EDUCATION · ANDROID LEARNING TABLET", description: "A compact kids educational tablet for home learning, entertainment and children-focused programs. Custom branding and packaging are available for private-label buyers.", highlights: ["Kids educational tablet", "Android 9", "1GB RAM + 16GB", "7-inch 1280×800 display"], galleryCount: 6, detailCount: 11, kids: true,
    specs: [["Display", "7-inch, 1280 × 800"], ["Operating System", "Android 9.0"], ["CPU", "MediaTek MTK6735 quad-core"], ["Use Case", "Kids education and learning"], ["Memory", "1GB RAM"], ["Storage", "16GB"], ["Wireless", "WiFi; Bluetooth stated in title, confirm final module"], ["Features", "Dustproof, drop-resistant shell, NFC listed"], ["Battery", "3000mAh"], ["Condition", "New"], ["Customization", "Private mold, logo and packaging options"], ["MOQ", "1 pc for sample · bulk pricing available"]],
    faqs: [["Is this a kids educational tablet?", "Yes. WB-TB-05 is specifically positioned for children, learning and educational entertainment."], ["What is the screen size?", "The product uses a 7-inch 1280 × 800 display."], ["Can I customize the kids tablet?", "Yes. Logo, packaging, language and selected appearance options can be discussed."], ["Does it include Bluetooth?", "Bluetooth appears in the product title; confirm the final wireless module before production."], ["What is the MOQ?", "Sample orders start at 1 unit; contact us for bulk pricing."]]
  }
};
