import type { MetadataRoute } from "next";

export const dynamic = "force-static";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://www.szweiboer.com";
  const urls: MetadataRoute.Sitemap = [
    { url: base, changeFrequency: "weekly", priority: 1 },
    { url: `${base}/laptops`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/dual-screen-laptop-oem`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/laptops/wb-lt-02`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/laptops/wb-lt-03`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/laptops/wb-lt-04`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/laptops/wb-lt-05`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/laptops/wb-lt-06`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/laptops/wb-lt-07`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/laptops/wb-lt-08`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/laptops/yg11`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/laptops/n16`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/laptops/jz58`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/laptops/dual-screen`, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/laptops/dual-screen/wb-lt-09`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/laptops/dual-screen/wb-lt-10`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/laptops/dual-screen/fd14`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/gaming-laptops`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/mini-pcs`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/mini-pcs/wb-mc-01`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/mini-pcs/wb-mc-02`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/mini-pcs/wb-mc-03`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/mini-pcs/wb-mc-04`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tablets`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/tablets/wb-tb-01`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tablets/wb-tb-02`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tablets/wb-tb-03`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tablets/wb-tb-04`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tablets/wb-tb-05`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/projectors`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/projectors/wb-pj-01`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/projectors/wb-pj-03`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/projectors/wb-pj-04`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/projectors/wb-pj-05`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/phones`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/phones/phone-1601928829240`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/phones/phone-1601928846599`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/phones/x27`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/phones/x16`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/all-in-one-pcs`, changeFrequency: "weekly", priority: 0.95 },
    { url: `${base}/all-in-one-pcs/uw30`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/all-in-one-pcs/k2`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/all-in-one-pcs/k4`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/all-in-one-pcs/z5`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/all-in-one-pcs/k7`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-01`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-02`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-03`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-04`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-05`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/portable-monitors/wb-mn-06`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/blog/choose-oem-gaming-laptop-manufacturer`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/n100-vs-ryzen-mini-pc-office`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/usb-c-portable-monitor-buying-guide`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/choose-android-tablet-supplier`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/projector-brightness-guide`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/oem-vs-odm-laptop-manufacturing`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${base}/blog/choose-dual-screen-laptop-oem-manufacturer`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/dual-screen-laptop-productivity-buyer-guide`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/dual-screen-laptop-vs-portable-monitor`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/dual-screen-laptop-oem-sampling-checklist`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/dual-16-inch-vs-16-plus-14-dual-screen-laptop`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/dual-screen-laptop-display-modes-oem-testing`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/weiboer-laptop-oem-supplier-quote-checklist`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/android-tablet-oem-sampling-checklist`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/mini-pc-oem-supplier-deployment-checklist`, changeFrequency: "monthly", priority: 0.85 },
  ];
  return urls.map((entry) => ({ ...entry, url: entry.url.endsWith("/") ? entry.url : `${entry.url}/` }));
}
