export type ProjectorProduct = {
  code: string;
  title: string;
  h1: string;
  eyebrow: string;
  description: string;
  highlights: string[];
  galleryCount: number;
  detailCount: number;
  specs: [string, string][];
  faqs: [string, string][];
};

export const projectorProducts: Record<string, ProjectorProduct> = {
  "wb-pj-01": { code:"HY300 PRO", title:"Smart Mini Projector OEM | 1080P, Android 13, 130 ANSI | Weiboer", h1:"HY300 Pro Smart Mini Projector — OEM / ODM Ready", eyebrow:"ANDROID 13 · 1080P SMART MINI PROJECTOR", description:"A compact Android 13 LED projector for home theater, outdoor entertainment and private-label programs. Configure logo, packaging and language for your market.", highlights:["Android 13","1920×1080 listed","130 ANSI lumens","30-120 inch projection"], galleryCount:6, detailCount:10, specs:[["Native Resolution","1920 × 1080 listed"],["Brightness","130 ANSI lumens"],["Operating System","Android 13"],["Projection Technology","LCD + LED light source"],["Contrast","1500:1"],["Projection Size","30-120 inches"],["Throw Distance","1-2.5m"],["Aspect Ratio","4:3 / 16:9"],["Light Life","30,000 hours"],["Focus / Keystone","Manual focus / automatic keystone"],["Speaker","Built-in 3W speaker"],["Weight","0.65kg"],["MOQ","1 piece"],["Customization","Logo, packaging and language options"]], faqs:[["Is the projector native 1080P?","The listing specifies 1920×1080 physical resolution and supports 1080P input."],["Does it use Android?","Yes. The listing specifies Android 13 and multi-language operation."],["What is the brightness?","The listing specifies 130 ANSI lumens."],["Can I customize the logo?","Yes. Logo, packaging and language customization are available."],["What is the MOQ?","The listing shows a 1-piece MOQ."]] },
  "wb-pj-02": { code:"WB-PJ-02", title:"M6 Portable LED Projector OEM | 380 ANSI, 720P, Smart Android | Weiboer", h1:"M6 Portable Smart LED Projector — OEM / ODM Ready", eyebrow:"M6 · 380 ANSI · PORTABLE SMART PROJECTOR", description:"A portable M6 LED projector for home theater, travel and smart entertainment. The platform supports 720P native output, HDMI, USB and custom private-label packaging.", highlights:["380 ANSI lumens","1280×720 native","32-150 inch projection","HDMI + USB"], galleryCount:6, detailCount:10, specs:[["Native Resolution","1280 × 720 / 720P"],["Brightness","380 ANSI lumens"],["Projection Technology","3.96-inch LCD + LED"],["Contrast","2000:1"],["Projection Size","32-150 inches"],["Throw Distance","1.0-4.5m"],["Aspect Ratio","4:3 / 16:9"],["Light Life","30,000 hours"],["Focus / Keystone","Manual focus / manual vertical ±15°"],["Power","70W · AC100-240V"],["Ports","TF card, AV, VGA, HDMI 1.4, USB 2.0, 3.5mm audio"],["Weight","1kg"],["MOQ","1 piece"],["Customization","Light customization and logo from artwork"]], faqs:[["Is it native 4K?","The native specification is 1280×720; the listing may mention 4K input support. We describe it as a 720P native projector."],["What is the brightness?","The listing specifies 380 ANSI lumens."],["Which ports are available?","HDMI 1.4, VGA, AV, USB 2.0, TF card and 3.5mm audio are listed."],["Can it be branded?","Light customization and logo from artwork are listed."],["What is the MOQ?","The listing shows a 1-piece MOQ."]] },
  "wb-pj-03": { code:"HY320 mini", title:"720P Android Mini Projector OEM | 200 ANSI, 180° Rotation | Weiboer", h1:"HY320 Portable Android Projector — OEM / ODM Ready", eyebrow:"ANDROID 11 · 720P · 180° ROTATING PROJECTOR", description:"A portable HY320 Android projector with 180° rotation for home theater, bedroom and outdoor entertainment programs. Custom logo and packaging are available.", highlights:["Android 11","720P native","200 ANSI lumens","180° rotation"], galleryCount:6, detailCount:10, specs:[["Native Resolution","1280 × 720 / 720P"],["Brightness","200 ANSI lumens"],["Operating System","Android 11"],["Projection Size","30-150 inches"],["Projection Distance","0.8-2m listed; another table states 1-4m, confirm before production"],["Rotation","180° free rotation"],["Wireless","Dual-band WiFi 6 + Bluetooth 5.0"],["Focus / Keystone","Manual focus / automatic keystone"],["Light Life","50,000 hours"],["Speaker","3W built-in speaker"],["Ports","USB, HDMI, audio and AC"],["Weight","1kg"],["MOQ","1 set"],["Customization","Logo, packaging and language options"]], faqs:[["Which Android version does it use?","The listing specifies Android 11."],["Is it native 720P?","Yes. The listed native resolution is 1280×720."],["What projection distance should I use?","The listing shows two different ranges, 0.8-2m and 1-4m. Confirm the final lens version before production."],["Does it support rotation?","Yes. The product is listed with 180° rotation."],["Can I customize the product?","Logo, packaging and language customization are available."]] },
  "wb-pj-04": { code:"M6", title:"M6 Pocket Projector OEM | 380 ANSI, 720P LED Home Theater | Weiboer", h1:"M6 Pocket LED Projector — OEM / ODM Ready", eyebrow:"POCKET HOME THEATER PROJECTOR", description:"A compact M6 pocket projector for home theater, travel and entertainment bundles. It shares the M6 platform with multiple configuration and packaging options.", highlights:["380 ANSI lumens","720P native","32-150 inch projection","Portable M6 design"], galleryCount:6, detailCount:10, specs:[["Native Resolution","1280 × 720 / 720P"],["Brightness","380 ANSI lumens"],["Projection Size","32-150 inches"],["Throw Distance","1.0-4.5m"],["Contrast","2000:1"],["Light Life","30,000 hours"],["Power","70W · AC100-240V"],["Ports","HDMI 1.4, VGA, AV, USB 2.0, TF card and 3.5mm audio"],["Weight","1kg"],["MOQ","1 piece"],["Customization","Light customization and logo from artwork"]], faqs:[["Is this a 4K projector?","The native specification is 720P. The listing may refer to supported input rather than native resolution."],["What is the brightness?","The listing specifies 380 ANSI lumens."],["Is it portable?","Yes. It is a compact M6 pocket projector with a 1kg listed weight."],["Can I add my logo?","Light customization and logo from artwork are listed."],["What is the MOQ?","The listing shows a 1-piece MOQ."]] },
  "wb-pj-05": { code:"YG300", title:"Mini Smart Projector OEM | Portable LED Home Theater | Weiboer", h1:"Mini Smart LED Projector — OEM / ODM Ready", eyebrow:"MINI LED · POCKET HOME THEATER PROJECTOR", description:"A low-cost pocket LED projector for gifts, entry-level home theater and portable entertainment programs. The listing contains conflicting brightness and resolution values, so we use the conservative native specification.", highlights:["320×240 native listed","10-20 ANSI lumens","24-60 inch projection","MOQ 10 sets"], galleryCount:6, detailCount:11, specs:[["Native Resolution","320 × 240p listed in detailed table; 1080P is a claimed supported input"],["Brightness","10-20 ANSI lumens listed; another row says 600 LED lumens, confirm before production"],["Projection Technology","LCD + LED"],["Projection Size","24-60 inches"],["Projection Distance","0.8-2m"],["Contrast","1000:1"],["Focus","Manual focus"],["Light Life","30,000 hours"],["Power","10-24W"],["Speaker","2W built-in speaker"],["Weight","0.5kg gross package weight listed; product weight requires confirmation"],["MOQ","10 sets"],["Customization","Light customization, artwork, samples and OEM options"]], faqs:[["What is the native resolution?","The detailed table lists 320×240p. The 1080P value appears to describe supported input, so confirm the final version before production."],["What is the actual brightness?","The listing shows 10-20 ANSI lumens and a separate 600 LED lumens value. We recommend confirming the ANSI rating with a sample."],["What is the MOQ?","The listing shows a 10-set MOQ."],["What projection size is supported?","The listed projection size is 24-60 inches."],["Can I order custom colors or packaging?","The listing shows multiple colors and OEM customization options; confirm final artwork and packaging requirements."]] },
  "wb-pj-06": { code:"WB-PJ-06", title:"M6 LED Projector OEM | 380 ANSI, 720P Home Theater | Weiboer", h1:"M6 LED Home Theater Projector — OEM / ODM Ready", eyebrow:"M6 · 380 ANSI · FACTORY LOGO CUSTOMIZATION", description:"An M6 LED projector platform for home theater, gaming and entertainment programs. Factory logo customization and private-label packaging are available.", highlights:["380 ANSI lumens","720P native","32-150 inch projection","Logo customization"], galleryCount:6, detailCount:10, specs:[["Native Resolution","1280 × 720 / 720P"],["Brightness","380 ANSI lumens"],["Projection Size","32-150 inches"],["Throw Distance","1.0-4.5m"],["Contrast","2000:1"],["Light Life","30,000 hours"],["Power","70W · AC100-240V"],["Ports","HDMI 1.4, VGA, AV, USB 2.0, TF card and 3.5mm audio"],["Weight","1kg"],["MOQ","1 piece"],["Customization","Logo, packaging and language options"]], faqs:[["Is it native 4K?","The native specification is 720P; any 4K wording should be confirmed as supported input before production."],["What is the brightness?","The listing specifies 380 ANSI lumens."],["Can I add a factory logo?","Yes. The title explicitly presents factory logo customization."],["What ports are available?","HDMI, VGA, AV, USB 2.0, TF card and 3.5mm audio are listed."],["What is the MOQ?","The listing shows a 1-piece MOQ."]] }
};
